### ISSUE TITLE
tslib_1 not defined when using typescript @RunAsWebWorker decorator

### ISSUE THREAD

**Issue by Fuzzylog1cza** [blacksquaresa/raww#1]
When using the @RunAsWebWorker decorator the compiled code is throwing an error:

```tslib_1 is not defined```

Presumably its expecting the typescript library to be somewhere it isn't.

**Comment by Fuzzylog1cza** [comment]
Resolved by using a promise instead of the async await keywords.

**Comment by blacksquaresa** [comment]
The issue here is that the TypeScript compiler uses helper methods to provide functionality that is not native to JavaScript. These methods are injected as part of the compilation process, and are not available to you at development time, so even if you know exactly which methods are used, there is no reference to them for you to pass. If you have the `importHelper` TypeScript config flag on, the helpers are not injected individually, but are referenced as part of the `tslib` library, which they assume you will have loaded (which is the case with this issue).

There are two basic work-arounds for this:

1. Import the `tslib` library, which gives you access to all the methods used by TypeScript. You then need to include references to the methods TypeScript uses in your function manually.
2. As of 0.6.0, the `RunAsWebWorker` decorator includes the tslib library as standard, both as the library, and as reference to each method in the library. If you use the decorator, there is nothing more you need to do.
